{% set name = "mecab-python3" %}
{% set version = "1.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mecab-python3-{{ version }}.tar.gz
  sha256: b150ad5fe4260539b4ef184657e552ef81307fbbe60ae1f258bc814549ea90f8

build:
  number: 0
  entry_points:
    - mecab-py = MeCab.cli:parse
    - mecab-py-info = MeCab.cli:info
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools_scm
    - mecab
  run:
    - python
    - mecab

test:
  imports:
    - MeCab
  commands:
    - pip check
    - mecab-py-info
  requires:
    - pip
    - unidic-lite

about:
  home: https://github.com/SamuraiT/mecab-python3
  summary: Python wrapper for the MeCab morphological analyzer for Japanese
  license: GPL-2.0-only OR LGPL-2.1-only OR BSD-3-Clause
  license_file:
    - COPYING
    - GPL
    - LGPL
    - BSD

extra:
  recipe-maintainers:
    - rynorris
    - henry-thompson
